#  Problem 4 

In [1]:
import numpy as np
import math
import sys

In [166]:
A = np.random.randint(-10, high = 10, size = 6)

In [167]:
A

array([-2,  5,  3,  8,  2,  0])

In [168]:
sentinel = -sys.maxsize - 1  
counter = 0
for i in range(0,len(A)):
    counter = counter + A[i]
    for j in range(0,len(A)):
        if counter > sentinel:
            sentinel = counter
        if counter < 0:
            counter = 0

In [169]:
print('Sum of the elements of the maximum sub array: ' + str(sentinel))

Sum of the elements of the maximum sub array: 18


# Problem 5

In [16]:
AA = np.random.randint(-100, high = 100, size = 15)

In [17]:
AA0 = np.random.randint(-100, high = 100, size = 1)

In [18]:
AA1 = np.append(AA, AA0)

In [19]:
aux = []
def linear_time_max_subarray(array):
    sentinel1 = -sys.maxsize - 1
    counter1 = 0
    for i in range(0,len(array)):
        counter1 = counter1 + array[i]
        if counter1 > sentinel1:
            sentinel1 = counter1
        if counter1 < 0:
            counter1 = 0
    return aux.append(sentinel1)

In [20]:
linear_time_max_subarray(AA)
linear_time_max_subarray(AA1)

In [21]:
aux

[137, 137]

In [22]:
print("Sum of the elements of the maximum subarray of A[1,...,j]: " + str(aux[0]))

Sum of the elements of the maximum subarray of A[1,...,j]: 137


In [23]:
print("Sum of the elements of the maximum subarray of A[1,...,j+1]: " + str(aux[1]))

Sum of the elements of the maximum subarray of A[1,...,j+1]: 137


In [24]:
AA

array([ 33,  38, -82, -70, -97, -61,  56,  -7, -63,  59,  78, -46, -12,
       -40, -56])

In [25]:
AA1

array([ 33,  38, -82, -70, -97, -61,  56,  -7, -63,  59,  78, -46, -12,
       -40, -56, -67])

In [26]:
np.mean(AA)

-18.0

In [27]:
np.mean(AA1)

-21.0625

In [28]:
if np.mean(AA) > np.mean(AA1):
    print("The maximum subarray of A[1,...,j+1] is the same as the maximum subarray A[1,...,j].") 
    print("Mean of the elements of A[1,...,j]: " + str(np.mean(AA)))
    print("Mean of the elements of A[1,...,j+1]: " + str(np.mean(AA1)))
    print("Mean of the elements of A[1,...,j] > Mean of the elements of A[1,...,j+1]")
if np.mean(AA) < np.mean(AA1):
    print("The maximum subarray of A[1,...,j+1] is not the same as the maximum subarray A[1,...,j], but it must contain the element A[j+1] of A[1,...,j+1].") 
    print("Mean of the elements of A[1,...,j]: " + str(np.mean(AA)))
    print("Mean of the elements of A[1,...,j+1]: " + str(np.mean(AA1)))
    print("Mean of the elements of A[1,...,j] < Mean of the elements of A[1,...,j+1]")

The maximum subarray of A[1,...,j+1] is the same as the maximum subarray A[1,...,j].
Mean of the elements of A[1,...,j]: -18.0
Mean of the elements of A[1,...,j+1]: -21.0625
Mean of the elements of A[1,...,j] > Mean of the elements of A[1,...,j+1]


In [29]:
if aux[0] == aux[1]:
    print("The maximum subarray of A[1,...,j+1] is the same as the maximum subarray A[1,...,j].") 
    print("Sum of the elements of the maximun subarray of A[1,...,j]: " + str(aux[0]))
    print("Sum of the elements of the maximun subarray of A[1,...,j+1]: " + str(aux[1]))
    print("Sum of the elements of the maximun subarray of A[1,...,j] = Sum of the elements of the maximun subarray of A[1,...,j+1]")
if aux[0] < aux[1]:
    print("The maximum subarray of A[1,...,j+1] is the same as the maximum subarray A[1,...,j].") 
    print("Sum of the elements of the maximun subarray of A[1,...,j]: " + str(aux[0]))
    print("Sum of the elements of the maximun subarray of A[1,...,j+1]: " + str(aux[1]))
    print("Sum of the elements of the maximun subarray of A[1,...,j] < Sum of the elements of the maximun subarray of A[1,...,j+1]")

The maximum subarray of A[1,...,j+1] is the same as the maximum subarray A[1,...,j].
Sum of the elements of the maximun subarray of A[1,...,j]: 137
Sum of the elements of the maximun subarray of A[1,...,j+1]: 137
Sum of the elements of the maximun subarray of A[1,...,j] = Sum of the elements of the maximun subarray of A[1,...,j+1]
